### ISSUE TITLE
wechat-backend和EC.Open.Backend的helpers.php 里 function 重复

### ISSUE THREAD

**Issue by oimken** [ibrandcc/ecommerce-open-api#6]
会出现以下错误提示：
```
Fatal error: Cannot redeclare generate_export_name() (previously declared in ..../ibrand/vendor/ibrand/wechat-backend/src/helpers.php:168) in
..../ibrand/modules/EC.Open.Backend/Store/src/helpers.php on line 219
```
提示重复的function有：
- generate_export_name
- generate_random_string
- generate_export_cache_name

**Comment by lifeagin** [comment]
> 会出现以下错误提示：
> 
> ```
> Fatal error: Cannot redeclare generate_export_name() (previously declared in ..../ibrand/vendor/ibrand/wechat-backend/src/helpers.php:168) in
> ..../ibrand/modules/EC.Open.Backend/Store/src/helpers.php on line 219
> ```
> 提示重复的function有：
> 
> * generate_export_name
> * generate_random_string
> * generate_export_cache_name

已修复
