### ISSUE TITLE
分类API无数据

### ISSUE THREAD

**Issue by oimken** [ibrandcc/ecommerce-open-api#7]
已经创建分类，分类里也有商品，但`/api/category` 无数据：

```
{"status":true,"code":200,"data":[]}
```

**Comment by lifeagin** [comment]
你好，前端分类页面展示的分类数据，考虑到美观度，是通过后台推广位形式来配置的。目前后台推广位管理正在开发，还没正式开发出来，预计下周可以开放。您目前可以参考demo里面的ibrand_advert，ibrand_advert_item这两张表来虚构数据以方便测试。谢谢
